apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp.q8
  labels:
    app: webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: webappdemo
          image: rao26599/webapp:v1
          args: [/bin/sh, -c, 'i=0; while true; do echo "$i: Hello"; i=$((i+1)); sleep 1; done']
