apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp.q8
  labels:
    app: webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: webappdemo
          image: rao26599/webapp:v1
          args: [/bin/sh, -c, 'curl  54.226.205.52:32220']
