apiVersion: v1
kind: Service
metadata:
  name: webappserviceq8
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 32220
      protocol: TCP
      targetPort: 80
  selector:
    app: webapp
